# Generated by Django 5.0.2 on 2024-02-06 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApplicationTask', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='lecture_hours',
        ),
        migrations.RemoveField(
            model_name='task',
            name='practical_hours',
        ),
    ]
